# Generated by Django 4.2.13 on 2024-05-17 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'category',
                    models.CharField(
                        choices=[
                            ('mobile', 'Mobile'),
                            ('work', 'Work'),
                            ('home', 'Home'),
                            ('fax', 'Fax'),
                            ('other', 'Other'),
                        ],
                        max_length=10,
                    ),
                ),
                ('number', models.CharField(max_length=15)),
                (
                    'contact',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='phones',
                        to='contacts.contact',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('email', models.EmailField(max_length=254, unique=True)),
                (
                    'contact',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='emails',
                        to='contacts.contact',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'category',
                    models.CharField(
                        choices=[
                            ('home', 'Home'),
                            ('work', 'Work'),
                            ('other', 'Other'),
                        ],
                        max_length=10,
                    ),
                ),
                ('address', models.TextField()),
                (
                    'contact',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='addresses',
                        to='contacts.contact',
                    ),
                ),
            ],
        ),
    ]
