# Generated by Django 4.2.13 on 2024-05-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "contacts",
            "0003_remove_contact_facebook_remove_contact_instagram_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="socialmedia",
            name="profile_image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
